import Images from "../../Static";

const DUMMY_DATA = [
  {
    title: "Continental PremiumContact™ 6",
    Model: "195/55 R15 85V",
    img: Images.OELogo,
    price: "₪340",
    total: "₪2,312",
    discount: "Save ₪408!",
    itemsLef: undefined,
    inStock: true,
    icon: Images.Tick,
  },
  {
    title: "Continental PremiumContact™ 6",
    Model: "195/55 R15 85V",
    img: Images.OELogo,
    price: "₪340",
    total: "₪2,312",
    discount: "Save ₪408!",
    itemsLef: "8 Tires Left",
    inStock: true,
    icon: Images.Warning,
  },
  {
    title: "Continental PremiumContact™ 6",
    Model: "195/55 R15 85V",
    img: Images.OELogo,
    price: "₪340",
    total: "₪2,312",
    discount: "Save ₪408!",
    itemsLef: "Back in 1 week!",
    inStock: true,
    icon: Images.Danger,
  },
  {
    title: "Continental PremiumContact™ 6",
    Model: "195/55 R15 85V",
    img: Images.OELogo,
    price: "₪340",
    total: "₪2,312",
    discount: "Save ₪408!",
    itemsLef: undefined,
    inStock: true,
    icon: Images.Tick,
  },
  {
    title: "Continental PremiumContact™ 6",
    Model: "195/55 R15 85V",
    img: Images.OELogo,
    price: "₪340",
    total: "₪2,312",
    discount: "Save ₪408!",
    itemsLef: undefined,
    inStock: true,
    icon: Images.Tick,
  },
  {
    title: "Continental PremiumContact™ 6",
    Model: "195/55 R15 85V",
    img: Images.OELogo,
    price: "₪340",
    total: "₪2,312",
    discount: "Save ₪408!",
    itemsLef: undefined,
    inStock: true,
    icon: Images.Tick,
  },
];

export default DUMMY_DATA;
